name: ml_ripc
dependencies:
  - bokeh
  - nbserverproxy
  - numpy
  - scipy
  - pandas
  # - matplotlib
  - ipython
  - seaborn
  - pip:
    - quilt
    # - jupyter-server-proxy
    # - jupyterlab_launcher>=0.5.0
    # - googledrivedownloader=0.3
