name: ml_ripc
channels:
  - nodefaults
dependencies:
  - python=3.5
  - numpy
  - bokeh
  - nbserverproxy
  - scipy
  - pip:
    - quilt
    - pandas
    - matplotlib
    - seaborn
      # - googledrivedownloader=0.3
